### ISSUE TITLE
Display score board

### ISSUE THREAD

**Issue by nano1342** [app4-quilles/Quilles#4]
As a user I want to see the scoreboard while playing.

Score board should a tab with 12 columns, and the number of lines should be the number of player + 1.
The first column is an unique number helping to identify each players.
The second column is used to display player's name.
The third to eleventh columns are used to display the number of pins the player made fall, and the twelfth one as well but it will be detailed further on.
The results should be dsplayed as such :
"-" means Gutter,
"/" means Spare,
"X" means Strike.
Examples of displays for columns 3 to 11 :
"3 4" means the player got 3 pins on its first shot and 4 more on its second shot.
"3 -" means the player got 3 pins on its first shot and put the ball in the gutter on its second shot.
"- 4" means the player put the ball in the gutter on its first shot and got 4 pins on its second shot.
"- -" means the player put the ball in the gutter on its first shot and second shot.
"3 /" means the player got 3 pins on its first shot and 7 more on its second shot, making it a spare.
"X  " means the player got all ten pins on its first shot.

The last column represents the pin the player got on its last turn.
There can be 3 shots in total, so we will use the same notation as column 3 to 11, but with some room for a third indication.
All possible displays for the twelvth column are the same as before, except for the case the player gets a spare or a strike.
In this case, we can have those displays :
"3 / -" means the player got 3 pins on its first shot and 7 more on its second shot, making it a spare, then a gutter.
"3 / 4" means the player got 3 pins on its first shot and 7 more on its second shot, making it a spare, then 4.
"3 / X" means the player got 3 pins on its first shot and 7 more on its second shot, making it a spare, then all ten pins.
"X 3 4" means the player got all ten pins on its first shot, then 3 and 4.
"X 3 -" means the player got all ten pins on its first shot, then 3 and a gutter.
"X - -" means the player got all ten pins on its first shot, then 2 gutters.
"X - 4" means the player got all ten pins on its first shot, then a gutter and then 4 pins.
"X 3 /" means the player got all ten pins on its first shot, then 3 and 7 more, making it a spare.
"X X -" means the player got all ten pins on its first shot, and its second, then a gutter.
"X X 4" means the player got all ten pins on its first shot, and its second, then 4.
"X X X" means the player got all ten pins on its first, second and third shot.

Requires #6 , #8 and #5 to be done.

**Comment by Picorims** [comment]
merged through pull request #13
