### ISSUE TITLE
Enter players

### ISSUE THREAD

**Issue by Picorims** [app4-quilles/Quilles#6]
As a user, I want to be able to enter the player's names with the CLI.
Characters supported are alphanumerical and underscores.

After the user has entered the first name, they can use the "play" keyword to stop entering players and begin playing.
As the user enters names, the list of players is displayed and updated on the screen.

**Comment by nano1342** [comment]
# @

- [ ] ### **[](url)**

**Comment by Baryum** [comment]
temporary asking how many players and starting game when all players are entered
